### ISSUE TITLE
Use SecuritySystem Characteristic

### ISSUE THREAD

**Issue by wuster13** [vectronic/homebridge-alarm-panel#2]
Hi I really like using this plug in for my DIY alarm, especially because of the HTTP api to control the alarm. So thank you! But I have a question, do you have any plans to use the Homekit built in securitysystem service that some other plugins utilize? Thanks again!

**Comment by vectronic** [comment]
Sorry I didn't answer this sooner - I wasn't getting notifications for issues.

I was just looking at this project again as I intend to switch it over to use the Security System Characteristic.

So maybe hang tight for a couple of weeks, or you could use this which I just came across as well: 

https://www.npmjs.com/package/homebridge-securitysystem

**Comment by vectronic** [comment]
Hi there,

There is a new version published here: https://www.npmjs.com/package/homebridge-alarm-panel

Let me know how it goes if you try it out!

NOTE - because it is almost a complete rewrite, I would suggest an uninstall of existing version, restart of homebridge, check accessories disappear in Home app, then install new version. 

Also, be aware some of the config property names have changed...
